version: "3.3"

networks:
  moopa-db:
    name: moopa-db

services:
  moopa-web:
    image: vekaverjj/moopa:latest
    container_name: moopa-web
    depends_on:
      - moopa-db
    environment:
      - CLIENT_ID=
      - CLIENT_SECRET=
      - GRAPHQL_ENDPOINT=
      - NEXTAUTH_SECRET=
      - NEXTAUTH_URL=
      - PROXY_URI=
      - API_URI=
      - API_KEY=
      - DISQUS_SHORTNAME=
      - DATABASE_URL=postgresql://username:password@moopa-db/table
    networks:
      - moopa-db
    ports:
      - 3000:3000
  
  moopa-db:
    image: postgres:15.4-alpine
    container_name: moopa-db
    environment:      
      - POSTGRES_DATABASE=table
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    networks:
      - moopa-db
